name: API Tests - Postman + Newman + Allure

permissions:
  contents: write

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      delay_request:
        description: 'Delay entre requests (ms)'
        required: false
        default: '400'
      user_login:
        description: 'Usu√°rio de login'
        required: true
        default: 'fulano@qa.com'
      pwd_login:
        description: 'Password de login'
        required: true
        default: 'teste'
      user_name:
        description: 'Nome do Usuario'
        required: true
        default: 'Teste API 2'
      user_email:
        description: 'Email do Usuario'
        required: true
        default: 'jocg24@qa.com.br'
      user_password:
        description: 'Password do Usuario'
        required: true
        default: 'teste'

jobs:
  tests-api:
    runs-on: ubuntu-latest
    env:
      SCRIPT_NAME: "test:api"
      NEWMAN_REPORT_FILE: 'reports/newman/report/report.html'
      ALLURE_REPORT_PATH: 'reports/allure/report'
      DELAY_REQUEST: ${{ github.event.inputs.delay_request }}
      USER_LOGIN: ${{ github.event.inputs.user_login }}
      PWD_LOGIN: ${{ github.event.inputs.pwd_login }}
      USER_NAME: ${{ github.event.inputs.user_name }}
      USER_EMAIL: ${{ github.event.inputs.user_email }}
      USER_PASSWORD: ${{ github.event.inputs.user_password }}

    steps:
      - name: Repository Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm

      - name: Run Tests
        run: |
          npm ci
          npm run ${{ env.SCRIPT_NAME }}

      - name: Generate Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: ${{env.NEWMAN_REPORT_FILE}}

      - name: Generate Report
        run: npm run allure:generate

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          publish_dir: ${{env.ALLURE_REPORT_PATH}}