name: API Tests - Postman + Newman + Allure

permissions:
  contents: write

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
      delay_request:
        description: 'Delay entre requests (ms)'
        required: false
        default: '400'

jobs:
  tests-api:
    runs-on: ubuntu-latest
    env:
      SCRIPT_NAME: "test:report"
      DELAY_REQUEST: ${{ github.event.inputs.delay_request || '400' }}
      NEWMAN_REPORT_FILE: "reports/newman/report/report.html"
      ALLURE_REPORT_PATH: "reports/allure/report"
      ALLURE_RESULTS_PATH: "allure-results"

      BASE_URL: "https://serverest.dev"
      USER_LOGIN: "fulano@qa.com"
      PWD_LOGIN: "teste"
      USER_NAME: "Teste API 2"
      USER_EMAIL: "jocg24@qa.com.br"
      USER_PASSWORD: "teste"

    steps:
      - name: Repository Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm

      - name: ðŸ“¦ Install Dependencies
        run: npm ci

      - name: Execute API tests (Newman)
        run: |
          npm run $SCRIPT_NAME

      - name: ðŸ“Š Generate Allure Report
        run: npm run allure:generate

      - name: Publish Newman Report
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: $NEWMAN_REPORT_FILE

      - name: ðŸ“¦ Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: $ALLURE_REPORT_PATH